$(document).ready((()=>{if(Date.now()>1672527599e3)return
if(localStorage.getItem("dismiss-end-of-year-sitenotice")>Date.now())return void $("#siteNotice").addClass("hide-notice")
localStorage.removeItem("dismiss-end-of-year-sitenotice"),$("#main-container").append('<div id="end-of-year-banner-wrapper"></div>')
let e=window.location.href.match(/\.onion/)?"http://w5j6stm77zs6652pgsij4awcjeel3eco7kvipheu6mtr623eyyehj4yd.onion":"https://www.kicksecure.com"
initEndOfYearSitenotice($("#end-of-year-banner-wrapper"),e,'\n        <h1>We want to <b>grow and improve</b> - please help Kicksecure!</h1>\n        \n        <div data-crypto-addresses=\'{\n          "payBitcoin": "3DaJWfHyLv4RVnvMD7K2Mz2AX2r3fwiQwV",\n          "payMonero": "84ozcSohQfoV6nRgGfaQ8uBvWphXAH8zDTTuotVnJWF1JMNQfvgNFdbEo4ZnJ9hxPMeYfJuUoWGH3MRaXCfbYk8sFFgm4XL",\n          "payEthereum": "0xf27EAe399f186600Dc6e5A418793C4A3D58a74e7"\n        }\'>\n        </div>\n        \n        <div>\n          <img src="/w/images/3/30/End-of-year-green.jpg" />\n          Kicksecure is an Open Source security power house and the basis for <a target="_blank" href="https://www.whonix.org">Whonix</a> - <b>providing great value to thousands of users</b>! \n          But only those who move forward continue to thrive. Would you support our next big leap? \n        </div>\n        \n        <div>\n          <img src="/w/images/2/2d/End-of-year-blue.jpg" />\n          For 2023 we\'re <b>improving the usability and enhancing the user experience</b>. We\'re also hardening the kernel against attacks, improving access control, adding a sandbox and many more features.\n        </div>\n        \n        <div>\n          <img src="/w/images/e/ef/End-of-year-yellow.jpg" />\n          We aim to create a high impact outreach with articles and videos to attract more users, get more feedback and in turn improve security for YOU!\n          <b>Would you consider a donation to keep Kicksecure independent</b> and help reach these new goals? Thank you.\n        </div>\n      ')
let n=$("#donate-end-of-year")
n.find(".btc .cbutton").attr("src","/w/images/thumb/2/29/BC_Logo_.png/40px-BC_Logo_.png"),n.find(".xmr .cbutton").attr("src","/w/images/thumb/0/05/Monero-symbol-1280.png/40px-Monero-symbol-1280.png"),n.find(".eth .cbutton").attr("src","/w/images/thumb/2/2c/Ethereumlogo.png/40px-Ethereumlogo.png"),$("#end-of-year-banner-modal").animate({opacity:1},1e3),n.find(".dismiss").on("click",(function(){$("#end-of-year-banner-wrapper").animate({height:0,opacity:0},1e3,(function(){$(this).attr("style","display:none !important;")}))}))}))

//# sourceMappingURL=dedb46e471cce1f837e9ade374af77fcecfe8fa2.map?__ws=forums.kicksecure.com
